### ISSUE TITLE
Not connecting to specified host

### ISSUE THREAD

**Issue by JadenDevon** [KasperFranz/BetterChunkLoader#23]
When BCL goes to connect to the database that I specify, it ignores the host that I put in the config and instead tries to insert the username and password using the host that the server is running on.
I am using BetterChunkLoader-5.2.0-3.5.0.jar and bclforgelib-1.1.20.jar

Here is my config.conf file:
https://pastebin.com/h4xJfNAn

Here is the log of the error:
https://pastebin.com/Ga9nUTYt

**Comment by KasperFranz** [comment]
please try this and paste the log output 

(it is now printing the config option for reference so please just maks your password.

http://ci.communitybuilt.net/job/BetterChunkLoader/30/artifact/build/libs/BetterChunkLoader-5.2.0-3.6.0-dev.jar

**Comment by JadenDevon** [comment]
https://pastebin.com/0Hzj0h0U

**Comment by KasperFranz** [comment]
And you have previously used this SQL on other plugins, since there isn't really anything I can see as wrong on this structure

**Comment by KasperFranz** [comment]
The reason is says @ the wrong is because that is what you are connecting to the database with

**Comment by JadenDevon** [comment]
I have used this SQL on a previous version of this plugin and it was working fine. 
It doesn't make sense that it would try and use the username and password on the server that I am connecting from and not the database itself. The username and password are supposed to be used to access the database, not the host that my server is running on. From the looks of that log, it is getting the correct info from the config, but ignoring the host that I enter and instead defaulting to the host that the server is on.

**Comment by KasperFranz** [comment]
The exception is telling you that the mysql server responded this user @ this address (where the connection is comming from) can't connect.

If it would try to connect to a mysql at your own ip (which I am guessing you don't have) it would give you a whole other error.

The error you have reported here is because of wrong credentials or missing permission to login from your servers ip address.

**Comment by JadenDevon** [comment]
If that is the case, then when I change the username in the config, then it should remain the same user. However, if I change the credentials in the config, the username on the error changes as well.

Edit:
I also want to emphasize that this was working on your initial build back when beyond was released. I will double check, but I am pretty sure that nothing on my end has changed since then

**Comment by KasperFranz** [comment]
If you change the username in the config then yes it will change in the output I'm the error yes.

As described in my latest messages it is wrong credentials, in mySQL this can both mean wrong username, wrong password or that the user isn't whitelisted on the mySQL server with the ip you are connecting from

**Comment by tolly765** [comment]
I know that it isn’t just trying to default to whatever host it is on in the plugin because I made a mistake with a server sided config and a local copy of it. Instead of the local copy of the server (my example was beyond) defaulting itself to running the database off of my local machine (which is the behaviour you are seeing atm), it still tried to connect to our server host. 

This was also shown to me when it tried to link across from two different remote servers at the same time (one with a skyblock server, one which hosted most of the databases on the network). If it didn’t work that way for you due to a fault in the code, then it wouldn’t be working for us now either. We both use the same build, yet we are experiencing different issues. My guess is that something is up with either the database address you have put on the config or the actual login details for said database.

**Comment by JadenDevon** [comment]
I know that it is not an issue with the address or the login details. I am currently working with one of my community managers to see if it is blocking the server port that the plugin is working from.
@KasperFranz Thanks for putting up with me.

**Comment by Shybella** [comment]
Yeah, something is wrong here when attempting to connect to MySQL. I have people constantly asking me why this isn't connecting to their DB.

**Comment by KasperFranz** [comment]
@Shybella your message does not make a lot of sense - this is working properly when using a MySQL server - if not please provide details
